trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    git config --global user.email "enxch@icloud.com"
    git config --global user.name "enochbalbuena"

    # Ensure GitHub remote is not added twice
    git remote remove github || true
    git remote add github https://enochbalbuena:${{ secrets.GITHUB_PAT }}@github.com/enochbalbuena/cookbook-corner.git

    # Push to GitHub
    git push --mirror github
  displayName: 'Sync Azure DevOps to GitHub'
